### ISSUE TITLE
Smooth changing values.

### ISSUE THREAD

**Issue by DeputyLOL** [MOARdV/AvionicsSystems#10]
I asked this about RPM before but I suspect it would be more practical to have it in MAS.
Having a value go smoothly from 0 to 1. It would function like the 'max rate change' but for the variable instead of the animation.

If not that, some sort of timer system. 
Let me know what you think.

**Comment by MOARdV** [comment]
Is this a perioidic variable that transitions smoothly, or is it a function to dampen a transition from 0 to 1 in a variable (like `fc.GetRCS()` transition 0 ... 1 instead of snapping 0-1)?

Is it for a prop animation, or for displaying on an MFD?

Give me an idea how you plan to use it, so I can figure out what works best design-wise.

**Comment by DeputyLOL** [comment]
I have a number of uses for it. The main one is for smoothly changing the overspeed and stall bars on the PFDs when flap position changes.

**Comment by MOARdV** [comment]
I haven't found a really good way to add a rate-limited change method.  It requires quite a bit of state, which needs to be tracked (like, "when did this start changing?", "what was its previous value?", "what is its current value?", etc.).  However ... for the flap position question, FAR knows the exact flap position on each part.  It might be possible to expose that variable (or for MAS to access it otherwise) so that you know the actual flap position, not just the snapped position.

**Comment by DeputyLOL** [comment]
thanks, it would be pretty sweet to have the actual flap position.

**Comment by DeputyLOL** [comment]
I wouldn't focus on this right now though, FAR is once again broken

**Comment by MOARdV** [comment]
Implemented as `fc.SetPersistentBlended()` ([see](https://github.com/MOARdV/AvionicsSystems/wiki/MASFlightComputerProxy2#fcsetpersistentblendedstring-persistentname-double-value-double-maxchangepersecond))
