### ISSUE TITLE
Request: "Click-And-Drag" control feature

### ISSUE THREAD

**Issue by Alexustas** [MOARdV/AvionicsSystems#113]
Now we have something similar in the stock "Throttle" module .
I'm sure that this feature is very useful for managing various control props, such as various levers and encoders.

As I imagine the work of this module. The user clicks on the collider and then moves the mouse along the vertical or horizontal axis, which changes the value of the specified variable.

In the config we specify:
- collider
- axis of the mouse movement
- something like resolution, i.e. how much the variable changes when the mouse moves one (or 10, or 100) pixel. **Optionally**, the dependence of the rate of change of the value is variable from the speed of the mouse movement. sharp and rapid movement - fast change of a variable, slow and smooth - slow change of a variable.

**Comment by MOARdV** [comment]
This will require some research to figure out how to make it work.  I think resolution will be difficult, because of different monitors.  For example, I have a 2560x1440 monitor, but I also test KSP in a 1920x1080 window, so the effect of resolution will be different depending on if I use full screen or window.  I think speed will be a better control.  But, like I said, I will need to research how to make this work.

**Comment by Alexustas** [comment]
resolution is just the first thing that came to my mind. probably, it is necessary to add the kind of  "sensitivity" item in the MAS settings menu

**Comment by MOARdV** [comment]
I think the best approach for the click-and-drag feature is to use a differential update.  For example, if the drag feature is configured to use mouse X, each time it moves to the right, it will report a small positive number.  Each time it moves to the left, it will report a small negative number.  This would be used as something like this:

```
dragEvent = fc.SetThrottle(fc.GetThrottle() + %DRAG%)
```
It could also be used on persistent variables using the fc.AddPersistent variants.

One question is how much the drag amount should be?  Proportional on screen size (easy, but may be very small numbers)?  Proportional on an absolute distance (like 100 pixels) (also easy)?

**Comment by MOARdV** [comment]
Here's the implementation.  It uses COLLIDER_EVENT, but adds three new config options:

* **onDragX**: Optional. Function that is called when the collider is clicked and the mouse is moved to the left or right.
* **onDragY**: Optional.  Function that is called when the collider is clicked and the mouse is moved up or down.
* **dragSensitivity**: Optional.  Default 1.0.  Controls the magnitude of the update value in the drag event callbacks.

New Keyword, only for `onDragX` and `onDragY`: `%DRAG%` When present, this keyword will be used to report the amount of change in the x or y position (depending on if this is onDragX or onDragY).  The amount is proportional to how far the mouse has moved since the last update, and it is guaranteed to be between -1.0 and +1.0.  For an example of use:

```
onDragX = fc.AddPersistentClamped("Backlight", %DRAG%, 0, 1)
```

This could be used with a single collider on a rotary switch to act as a brightness control.

**Comment by MOARdV** [comment]
Available now on [DropBox](https://www.dropbox.com/s/qo4a5yxz3qa6065/AvionicsSystems-0.21.0b1.zip?dl=0).

**Comment by Alexustas** [comment]
Question.
I'm **very** interested in the possibility of creating double concentric encoders, in particular for controlling radio receivers, but not only for this. 
How it could work: I click on the encoder prop  and drag horizontally changing the integer part of the frequency, or drag it vertically and change the fractional part of the frequency.

In order for it to work, I need to determine the prevailing direction of drag and use it only, ignoring the rest. Because it is almost impossible to drag only horizontally or only vertically.

Is it possible to somehow implement it?

**Comment by Alexustas** [comment]
here's how it looks in reality

video
https://youtu.be/mXS_wEJCNN8

**Comment by MOARdV** [comment]
> Is it possible to somehow implement it?

I can add an option like "singleAxisDrag" that will allow only one axis to report during a drag, whichever one moves the most on first update.

**Comment by theonegalen** [comment]
Oh this will help with AJE throttle quadrants! Huzzah!

**Comment by MOARdV** [comment]
'singleAxisDrag' will be in the next release.  Available on [DropBox](https://www.dropbox.com/s/sapygr4c1a4j8f7/AvionicsSystems-0.21.1b1.zip?dl=0) beta.
