### ISSUE TITLE
Kramax Autopilot Support

### ISSUE THREAD

**Issue by theonegalen** [MOARdV/AvionicsSystems#116]
I've never been a user of Kramax Autopilot, but with Pilot Assistant no longer supported, I've given it a shot. It actually has a lot of the features I've been looking for regarding waypoint following and flight planning, as well as PA's ability to hold heading/bank, etc. 

Would it be possible for MAS to support Kramax the way RPM supports PA? Basically, I'd be looking for all the same variables as RPM has for PA, as well as the ability to build, save, load, and fly flightplans that Kramax brings.

I'd also like to integrate a top-down Garmin-style GPS with Kramax or stock waypoints drawn over the SCANsat map, with lines drawn in between the waypoints.

If MAS has these functions already possible without Kramax, please disregard. I still don't know what is and isn't possible with MAS because I am code illiterate.

**Comment by theonegalen** [comment]
Kramax Continued thread: https://forum.kerbalspaceprogram.com/index.php?/topic/150846-131-kramax-autopilot-continued-course-guidance-and-auto-land-for-spaceplanes/&

**Comment by lazar2222** [comment]
MechJeb has airplane autopilot now (not as fully featured as Kramax) so it might be easier to implement it since we already have MechJeb support.

**Comment by MOARdV** [comment]
Reviewing open issues - LGG added a couple of hard dependencies to this mod (Toolbar controller and click through blocker), which means adding extra mods to work on this one.  Since I'm not using the Kramax AP, and I don't fly planes much (at all) anyway, that's a lot of overhead to get this mod supported.

Besides, MAS natively supports navigation beacons (and alexustas has provided a lot of them). I think it may make more sense for me to roll an autopilot / flight plan executor into my nominal MAS autopilot system.  Having a database of nav beacons will make it easier to create new flight plans down the road.

**Comment by theonegalen** [comment]
I understand the difficulty regarding LGG's mods and their new dependencies. Thanks for looking into it. Sorry I was away so long.

Should I start a new issue with autopilot info?

**Comment by MOARdV** [comment]
> Should I start a new issue with autopilot info?

No worries being away.  You can start a new thread for an autopilot if you like - I've got a poor-man's autopilot on the kOS Terminal prop currently (it holds heading, pitch, and roll using SAS), but it wouldn't be mistaken for anything as thorough as an autopilot.

**Comment by theonegalen** [comment]
Sounds good. I'll get on that next week, since I'm going to be very busy until next Monday.
