### ISSUE TITLE
Gravity Turn-like Ascent Autopilot

### ISSUE THREAD

**Issue by MOARdV** [MOARdV/AvionicsSystems#124]
This would work like the MJ ascent autopilot, although it also has the ability to improve launch parameters as well.

**Comment by Alexustas** [comment]
I do not really like a large number of third-party add-ons, because of their unpredictability in the future, and also because for their work it is necessary to add additional props to the interior, which will be completely useless if the user does not use these mods. IMHO.

I really like when MAS itself acquires new abilities )))

**Comment by MOARdV** [comment]
I did think about writing a launch autopilot.  Maybe I can do some more research on it, instead. :)

**Comment by MOARdV** [comment]
Maybe look into an airplane autopilot, too (similar to [Kramax Autopilot](https://forum.kerbalspaceprogram.com/index.php?/topic/150846-141-kramax-autopilot-continued-course-guidance-and-auto-land-for-spaceplanes/)).

**Comment by MOARdV** [comment]
I think the current version of the autopilot needs to be scrapped and redone.  Right now, it is built into the main MAS module, which is a problem if someone switches to external view (that will cause it to shut off).  The auto pilot needs to be a separate module.

**Comment by snakeru** [comment]
Just my 2 cents. Here is the launch sequence I use when using MAS:
1) throttle up, ignite, release clamps
2) wait until vessel reaches 50 or 75 or 100 or 120 or 150 m/s. Which one - depends on TWR. With 1.2 TWR that would be 150, with 2.0 - 50.
3) Rotate and hold to 80 degrees, wait until surface prograde matches the vessel orientation
4) switch SAS to follow prograde
5) Optionally throttle down until 10km altitude
6) At 20...25km switch to following orbital altitude
**** Let's say we are targeting 150km orbit ****
7) At about 130km Ap switch SAS to stability assist and point to horizon
8) Keep throttling down as the Ap nears the 150km. DO NOT THROTTLE DOWN TO 0!!! That is important because engines could not be reignited (even the orbital ones).
9) As we are close to Ap (say, 30...40 seconds to go) switch SAS to follow prograde again.
10) Keep playing with throttle to keep Ap reasonably in future (20...30 seconds). The closer to Ap we are, the nearer in future it has to be. 
11) In the ideal case the engine shut down should coincide with Pe matching Ap and time to Ap being zero. 
--------------
Couple of notes:
1) A scaled-up systems require higher velocities to achieve orbit. So I do not pay attention to the velocity, instead I only track Pe and Ap.
2) Sometimes the TWR of the upper stage is not enough and I have to nose up to keep Ap in the future. It is however important to not nose-up too high - we don't want to waste too much dV on keeping Ap in front of us.
3) I can totally try to implement this alogrithm in Lua, but I'll need help with bootstrapping. For example, I need a very simple Autopilot that:
  *) can be switched by a toggle
  *) is written in LUA
  *) can perform a sequence of actions that takes time (ignition and clamps release should be apart)
  *) rotates to 80 degrees at 50 m/s
  *) can read the vehicle description (in the same way as AGs do)

**Comment by snakeru** [comment]
Actually, if MAS can be integrated with kOS then all we need is a module that can generate a kOS code basing on the constants taken from the vessel description (something like AUTOPILOT=ROT=150;Ap=150;THRDN=0.6;THRUP=10)

**Comment by snakeru** [comment]
I did my own version of it.
It is currently based on LUA, but only because I wasn't aware of TRIGGER_EVENT so I might eventually rewrite it.

It uses MAS Autopilot + SAS Prograde modes. The MAS Autopilot seems to be not very reliable if the correction angle is big. For example, if the current attitude is, say, 50 degrees east and it is commanded to take 0 degrees east, then it might as well go about 20-30 degrees south before reaching the goal (which happens in about a minute). So I have to help it a bit. 
However with small angles (like going from 90 to 80 degrees east) it works perfectly so that's not such a big deal.

![image](https://user-images.githubusercontent.com/72657/56562036-cd9c6280-65a8-11e9-998a-3e8f08db44db.png)

**Comment by snakeru** [comment]
A small follow up: while I am satisfied with it there are already a couple of features not possible because of #266 :-)
These are namely: preconfiguring switches on load and triggering action groups (e.g. discarding the LES tower).

**Comment by MOARdV** [comment]
I'm punting on the feature - it duplicates two existing mods, and I think my time is better spent not reinventing that wheel.
