### ISSUE TITLE
Feature Request: Science controls.

### ISSUE THREAD

**Issue by theonegalen** [MOARdV/AvionicsSystems#141]
I'd like to be able to control science experiments from MAS IVAs, and place Science controls the same way we have electrical controls.

I propose something like this, based on the solar panel functions:

**fc.ScienceCountTotal()** would return the total number of science parts (counting ModuleScienceExperiment, DMModuleScienceAnimate, WBIModuleScienceExperiment (from @Angel-125's MOLE), TSTSpaceTelescope, InterstellarTelescope, and StationExperiment (from Station Science)) if possible), MAS automatically assigning IDs to all of those on vessel load, and then being able to display a selectable list of whatever experiment is installed on an MFD. EVA reports stored on the vessel could be appended to the bottom of the list.

**fc.ScienceTypeTotal()** would return all the different types of science experiments onboard: Crew Reports, Goo Experiments, etc.

**fc.ScienceType(double ScienceID)** would return the text string descriptor of the specified science experiment, e.g. "Mystery Goo" or "Materials."

**fc.ScienceStatus(double ScienceID)** would return 0 for an experiment that had not been run, 1 for an experiment that has results, and -1 for an experiment that has been transmitted and cannot be rerun (like the Mystery Goo and Materials Bay).

**fc.ScienceBiome(double ScienceID)** would return the descriptor of what biome the specified science experiment was run in (MUN'S HIGHLANDS or LAUNCHPAD, etc). Returns 0 if the experiment holds no data.

**fc.ScienceSituation(double ScienceID)** would return the descriptor of what situation the specified science experiment was run in (IN SPACE HIGH, LANDED, SPLASHED, FLYING LOW, etc). Returns 0 if the experiment holds no data.

**fc.ScienceTransmitScaler(double ScienceID)** would return the xmitDataScalar field from ModuleScienceExperiment, DMModuleScienceAnimate, StationExperiment, or TSTSpaceTelescope for the specified science experiment. I'd prefer it display as a percentage, if possible. Returns 0 if the experiment holds no data.

**fc.SciencePointsReturn(double ScienceID)** would return how many science points the selected stored experiment is worth if it is returned to the KSC. Returns 0 if the experiment holds no data.

**fc.RunScience(double ScienceID)** which would run the science for the specified experiment. Entering 0 for ScienceID would run all science experiments available. Returns 0 if none available?

**fc.RunScienceType(double ScienceTypeID)** would run the science for the specified type of experiment as long as at least one of that type was available. Returns 0 if none available?

**fc.ViewScience(double ScienceID)** would pop up the stock UI for the specified experiment, the same as in the right click menu.

**fc.ResetScience(double ScienceID)** would reset the the selected experiment. Entering 0 for ScienceID would reset all science experiments and dump all data.

**fc.TransmitScience(double ScienceID)** would transmit the data for the specified experiment, so long as the vessel is connected to CommNet or however it works with RemoteTech. Entering 0 for ScienceID would transmit all available and transmittable experiments.

**fc.CleanScience(double ScienceID)** would reset experiments like the Materials Bay and Mystery Goo so long as a Scientist of sufficient skill was aboard. Entering 0 for ScienceID would clean all available experiments.

Instead of using a value based on what experiments are available, perhaps a lookup table for ScienceTypeID would be best? (1 = Crew Report, 2 = Mystery Goo, and so on) I'm thinking of the way the resource list and resourceID works, although I'm not sure how helpful that would be. Would it be possible to make that sensitive to modulemanager, so that we could use :NEEDS[DmagicScienceAnimate] or whatever to append new ScienceTypeID names?

I don't have a lot of knowledge about how all of this works under the hood, so I'm not sure how computationally expensive it would be to keep tabs on the total number of science experiments, when and where they'd been run, etc, especially as things change when craft are docked to other craft.

**Comment by theonegalen** [comment]
This is a mockup of my MFD page idea.

https://i.imgur.com/w5Gr5YH.png

**Comment by theonegalen** [comment]
This is a mockup of my MFD idea. The carot shows which experiment is selected, and different buttons on the outside of the MFD would use various of the functions mentioned above.

**Comment by theonegalen** [comment]
It would also be nice if we could control the science containers using ModuleScienceContainer. I propose:

**fc.ScienceContainerCountTotal()** - counts the parts with ModuleScienceContainer.

**fc.ScienceContainerTitle(double ScienceContainerID)** - gives the part title of the specified science container.

**fc.ReviewScienceContainerStorage(double ScienceContainerID)** - opens the Squad UI for the stored experiments in the specified Science container. Same as "Review Stored Data" in the right-click action menu.

**fc.FillScienceContainer(double ScienceContainerID)** - puts all experimental data in range into the specified Science Container. Same as "Store Experiments" in the right-click action menu. Requires Scientist trait onboard?

**Comment by MOARdV** [comment]
Thanks for a very detailed proposal - I've tried a few times to figure out what would be appropriate for science, but I never got very far (probably because I play only in sandbox).  This gives me enough of a framework to put something together.

**Comment by MOARdV** [comment]
It looks like Angel-125's WBIModuleScienceExperiment is derived from stock ModuleScienceExperiment.  I think DMagic's DMModuleScienceAnimate is as well.  As long as the mod's modules are based on the related stock manuals, I'll be able to support them (as long as they don't have special requirements beyond the basic science module).

**Comment by JonnyOThan** [comment]
Just like in RPM, I’d love to try to tackle this.  Should I fork the repo and submit a pull request when I’ve got something ready?

**Comment by theonegalen** [comment]
Here's a basic design for your consideration.

https://i.imgur.com/5F6eJmQ.jpg

**Comment by MOARdV** [comment]
> Just like in RPM, I’d love to try to tackle this. Should I fork the repo and submit a pull request when I’ve got something ready?

Please feel free to do so.  I think I stubbed in the beginning of some science code a while back.  Search MASVesselComputerModules.cs for the Science region.  I think this would be the best place to interface with the related KSP components, but I don't know what the MAS data structures would look like that track results.

**Comment by snakeru** [comment]
I have a couple more ideas that would probably be useful for implementing props:
1. "triggerOne" A function that will invoke an action on just a single part, even if several are present.

2. "canTrigger" A function that will return the number of units on which a specific action could be triggered. Example: "Observe Mystery Goo" would be 1 if there are three mystery goo units onboard and one of them holds results of the experiment and another one was used and results were removed.

3. "potentialScience" A function that will return floating point of the possible science gains in the current biome for the specified experiment.

4. "hasScience" true if there is a report for the current biome already on-board

The function names are purely for demonstration purposes of course, you will probably have much better idea of how to name them.

Example:
There are 4 Mystery Goo units onboard and one science container. There is _no_ scientist onboard.
Unit 1: observed, holds results of "in upper atmosphere". Science value: 3.0.
Unit 2: not observed.
Unit 3: not observed.
Unit 4: inoperable (needs cleaning by scientist)
Science container holds the result of "in space low". Science value: 15.0/20
Science center holds the following reports:
in space low: 1.0/20
in higher atmosphere: 12.0/16
flying over water: 11.99/12
splashed down: 8.0/10
If mystery goo is observed once "in space low" then it will bring us 16 points.

* Vessel is currently "in space low" and is heading towards ground. 
canTrigger("observe", "mysterygoo") returns 2
canTrigger("reset", "mysterygoo") returns 1 (inoperable can't be reset, but observed can)
canTrigger("clear", "mysterygoo") returns 0 here and below (no scientist onboard)
potentialScience("mysterygoo") returns 0.2 (=1-(1+15)/20)
hasScience("mysterygoo") returns true (container has it)

[user clicks a prop now, triggerOne is executed]
triggerOne("observe", "mysterygoo") observes unit 2 or 3. Doesn't matter which, but _only one_ of them. The triggered unit now holds 15 science for "in space low". Let's say this is unit 3.
canTrigger("observe", "mysterygoo") returns 1
canTrigger("reset", "mysterygoo") returns 2
hasScience("mysterygoo") returns true (container and unit 3 have it)
potentialScience("mysterygoo") returns 0.2 still (=1-(1+15)/20) (the onboard values do not add up. The formula is (science_center + max(all,of,onboard,parts))/total_possible)

* Vessel is currently "in upper atmosphere" and is still heading towards ground. 
canTrigger("observe", "mysterygoo") returns 1
canTrigger("reset", "mysterygoo") returns 2
potentialScience("mysterygoo") returns 0.0625 (=1-(12+3)/16)
hasScience("mysterygoo") returns true (unit 1 has it)

* Vessel is currently "flying low over water" and is still heading towards ground. 
canTrigger("observe", "mysterygoo") returns 1
canTrigger("reset", "mysterygoo") returns 2
potentialScience("mysterygoo") returns 0.000833 (=1-11.99/12)
hasScience("mysterygoo") returns false

[user clicks a prop now, triggerOne is executed]
triggerOne("observe", "mysterygoo") observes unit 2 (the only remaining). The triggered unit now holds 0.005 science for "flying low over water".
canTrigger("observe", "mysterygoo") returns 0
canTrigger("reset", "mysterygoo") returns 3
potentialScience("mysterygoo") returns 0.0004167 (=1-11.995/12)
hasScience("mysterygoo") returns true (unit 2 has it)

* Vessel is currently "splashed down".
canTrigger("observe", "mysterygoo") returns 0
canTrigger("reset", "mysterygoo") returns 3
potentialScience("mysterygoo") returns 0.2 (=1-8/10)
hasScience("mysterygoo") returns false

[user clicks another prop now, triggerOne is executed]
triggerOne("reset", "mysterygoo") resets a unit.
canTrigger("observe", "mysterygoo") returns 1
canTrigger("reset", "mysterygoo") returns 2
potentialScience("mysterygoo") returns 0.2 (=1-8/10)
hasScience("mysterygoo") returns false

[user clicks first prop now, triggerOne is executed]
triggerOne("observe", "mysterygoo") resets a unit. The unit now holds 1.5 science.
canTrigger("observe", "mysterygoo") returns 0
canTrigger("reset", "mysterygoo") returns 3
potentialScience("mysterygoo") returns 0.05 (=1-(8+1.5)/10)
hasScience("mysterygoo") returns true (one of containers onboard has it)

[user clicks yet another prop now, triggerOne is executed]
triggerOne("collect", "sciencecontainer") collects science from units onboard. Units 1 and 2 are rendered inoperable. Unit 3 remains holding the report because containers refuse to have duplicate reports).
canTrigger("observe", "mysterygoo") returns 2
canTrigger("reset", "mysterygoo") returns 1
potentialScience("mysterygoo") returns 0.05 (=1-(8+1.5)/10)

**Comment by snakeru** [comment]
Given the functions above the following instrument could be implemented:

Two-Light: benefit of an experiment (potentialScience is in 0...0.02...0.25...1.0) None, one or two lights can shine at the same time. 
-OR-
Three-Light: benefit of an experiment (potentialScience is in 0...0.005...0.15...0.5...1.0) None, one, two or three lights can shine at the same time. 

Light: can make an experiment (canTrigger > 0)

Light: has science for current biome (hasScience is true)

Toggle: observe. Fires triggerOne(observe, x) and returns to original position

Toggle: clear. Fires triggerOne(reset, x) and returns to original position.

**Comment by snakeru** [comment]
A mock up:
![goo2](https://user-images.githubusercontent.com/72657/50734204-f46e8e80-119b-11e9-961a-e50f6539f897.png)

**Comment by snakeru** [comment]
Looking some more at the mockup of @theonegalen 

* "Reset" and "discard" are probably the same function, I don't see a use-case for them to be different.

* The "DONE" in my mockup can probably be replaced with "STORED".

* My mockup still misses:
"restorable" flag indicator + the "restore" toggle
"transmittable" flag indicator + XMIT toggle + "allow partial" toggle.

The "restorable" must light if: there is a functioning science lab. Just having a scientist onboard is not enough.

The "transmittable" must light if: antenna is deployed AND there is an uplink to control center (Kerbin or a mobile center) AND (there is enough energy to transmit the full load AND "allow partial" is disabled" OR there is enough energy to transmit at least a single data packet AND "allow partial" is enabled").

* If we want to make it more compact then we can drop the "Mystery Goo (TM)" at the top and replace it with a rotary switch as on the @theonegalen's mock.

**Comment by snakeru** [comment]
Tried to implement some PROPs using the existing functionality: https://github.com/MOARdV/AvionicsSystems/commit/25f8817a7dcdc4ef5f7191784932cc7cc058e165

It kinda works, but not quite. Reseting experiments clears the materials bay and mystery goo, which should not happen. This can be fixed via LUA scripting though. So I'll be waiting until we have some of the functions described above.

**Comment by MOARdV** [comment]
Okay, I'm finally starting to look into this.  I am going to make some changes to names of the functions.

Anything starting `Experiment` refers to a specific ModuleScienceExperiment.  So, `fc.ExperimentCount()`, `fc.ExperimentScienceType()`, etc.

I am thinking about using `Science` to refer to the type of experiment (crew observation, mystery goo, barometer), although I still need to get farther into the process, to see if the name holds up.

**Comment by MOARdV** [comment]
> The AutomatedScienceSampler would probably be a good source of ideas, how the science value and if experiment was already run be extracted

That's exactly the sort of information I need to understand the science modules, and it's convenient not to have to figure it out myself.  Thanks for finding that.

**Comment by Angel-125** [comment]
@MOARdV That looks very cool. I'm happy to make sure that WBI science experiments will be compatible with the IVA system. :)

**Comment by MOARdV** [comment]
`fc.TransmitScience(scienceId)` may be a challenge.  I see where I can transmit science from ModuleDataTransmitter, but that only has the effect of pressing the "Transmit Data" button on the part menu for an antenna (which looks like it's a "Transmit All the Things!" function).

The experiments and containers don't have a "Transmit Me" option built in to them, so I need to figure out how the experiment UI chooses to transmit a specific science thing.

On the up side, I'll be able to add functions for display the status (transmission rates, costs, etc) of various data transmitters.

**Comment by MOARdV** [comment]
Okay, good progress over the last day - I can now transmit science from any selected experiment, or from any selected data container.  I can also tell a container to fill itself up.  There are functions to report the capacity of a container, and how much is currently in it.  And there are some functions to peruse the data transmitters that support science.

I think the only major hurdles to feature complete are the clean / reset functions, and that's mostly because I need to make sure I understand what the limitations are for those, and that MAS obeys those limitations (such as, some experiments can only be reset on EVA).  Plus a couple of the other helper features, like RunScienceType.

**Comment by MOARdV** [comment]
I have a question for the people who are familiar with the Science aspect of KSP.  One of the functions requested here is 'CleanScience()', which is intended to reset a science experiment like the Mystery Goo.  However, the normal game UI doesn't allow me to do that, and the relevant function in the KSP API is named in a way that suggests that it's something that can happen only on EVA.

If the stock game does not allow a remote cleaning, I don't think MAS should, either - that strikes me as a cheat.  Am I misunderstanding the stock game behavior?

**Comment by MOARdV** [comment]
Since I'm chattering about the Science feature ...

One problem I see is that running an experiment puts up the science dialog.  If you've shut off the UI overlays, you won't see the dialog, but it's still there (I haven't checked to see if it blocks clicks, alas).  It looks like the data is stored, but I'd like to find a way to run experiments without triggering the UI.

**Comment by theonegalen** [comment]
Yes, by default, science experiments like the mystery goo can only be cleaned for reuse by a Scientist kerbal on EVA. Having recently learned about the real world EVAs to retrieve science samples from the Apollo Service Module on the way back from the Moon, I think it is entirely reasonable to eliminate the function to do that from my feature request.

It would be very nice if you could bypass the science dialog. Would there be a way to get some of the same information that dialogue shows, like the description text of the science return?

**Comment by MOARdV** [comment]
> It would be very nice if you could bypass the science dialog.

Agreed. I'll ask around on the forum to see if anyone's found a way to do so.

> Would there be a way to get some of the same information that dialogue shows, like the description text of the science return?

Maybe?  I haven't looked, but it's got to be there somewhere.  Probably the biggest issue will be that some text may not fit on a single line on the MFD, which means using `fc.ScrollingMarquee()` to display it, since I don't really want to add the complexity of text layout with word wrapping.

**Comment by snakeru** [comment]
The stock game allows to reset the MisteryGoo & the like. This goes like this:
1) You make the experiment (by interacting with menus or using an action group)
2) The science window pops up.
3a) you click the "reset experiment"
3b) you click the "store data)
4b) you later review the data (by interacting with menus or using an action group)
5b) The science window pops up again.
6b) you click the "reset experiment".

So it IS possible. BUT even in the stock game this totally feels like a cheat and I am not sure why Squad even added this. So I am also in favor of skipping this feature. Knowing the fact whether a particular experiment was already done in the current biome is like 1000% more important.
----------
I play MAS exclusively with UI off. So when I click my self-made "Make Science" prop I know for sure that an invisible science window pops up. But it doesn't bother me because it does not prevent any clicks. Once I'm done with the mission I enable the UI (because I removed the "recover me" prop and close all these science windows before clicking "recover". If you are worried about that window may be you should research how to auto-click this "store science" UI button.
----------
Transmitting science is significantly less important in stock because of incomplete value gained from that (from certain experiments). But if you have a manned mission you know that you'll return to Kerbin one day so you can afford just keeping that science around until that time. And if you play a non-manned mission that you don't have UI turned off (and don't use MAS) anyway.

I would guess that it may be different with certain mods.

**Comment by MOARdV** [comment]
I found a way to generate results without the UI popping up, and, as far as I can tell, it works.

I still need to add a test for whether an experiment has already been run (the "hasScience" function), and I need to add some tests to the RunExperiment functions so they obey restrictions (some experiments may require a scientist on board, for example).

There is also the "potentialScience" function @snakeru requested.  Where does "total_possible" come from in this formula?

**Comment by snakeru** [comment]
I don't know if that's of much help, but here is an illustration to what I meant by the "total_possible". That's the maximum value one can get from an experiment by running it many times. But I suspect you knew that already and the question was about something else.

<img width="1062" alt="screenshot-20192802-235746" src="https://user-images.githubusercontent.com/72657/53604482-ee51c880-3bb4-11e9-87f1-fd7e20d17493.png">

**Comment by snakeru** [comment]
Accordingly, the "Atmospheric Pressure Scan while in space high over Ceti" would have potentialScience() value of about 0.3 in the screenshot above.

**Comment by MOARdV** [comment]
> I don't know if that's of much help, but here is an illustration to what I meant by the "total_possible".
This is the screenshot from the science facility's "archives".

No, this is what I was asking.  I never have played KSP in Career or Science, so I do not understand how to compute the total possible value.  I think I need to find the Current Data Value amount.

**Comment by MOARdV** [comment]
Okay - I do not see an easy way to compute the "potentialScience" value.  I can look up an experiment's value and maximum potential value in a given biome (like "Atmospheric Pressure Scan while flying at Kerbin"), but I do not see how that correlates to any other values.  For the time being, I am going to skip that capability until there's some time for people to try the MAS Science functions.

I'm declaring this feature fully implemented with v0.95.4 this weekend.  I would very much appreciate feedback on the functionality in-game - there may be bugs or other mistakes, but I have not used the science feature enough to believe I can recognized them.

**Comment by theonegalen** [comment]
That'll be my first experiment ;) with MAS, then
