### ISSUE TITLE
Extension to fc.Conditioned

### ISSUE THREAD

**Issue by theonegalen** [MOARdV/AvionicsSystems#146]
I'd like to use a custom persistent variable with fc.Conditioned. My Warbird Cockpits mod uses a custom variable PERSISTENT_WARBIRD_BATTERY_ON to simulate connecting the battery before anything else can be done - giving a cold and dark cockpit. So I'd like to be able to use a persistent variable as part of the fc.Conditioned condition. It would be set with the other conditioning variables in MASFlightComputer. If not included in the MASFlightComputer, it is considered to be on all the time.

for example:
	gLimit = (a ridiculously large number)
	baseDisruptionChance = 0.0
	requiresPower = false
	powerOnVariable = Warbird_Battery_On

**Comment by MOARdV** [comment]
I'd prefer not adding special-case values like that, primarily because you can achieve the same result inside `fc.Conditioned()` using this idiom:

```
variable = fc.Conditioned(fc.GetPersistentAsNumber("Warbird_Battery_On") * fc.Whatever())
```

As long as Warbird_Battery_On is a toggle value (either 0 or 1), it will accomplish the same thing.  I've got several props that use that same approach (such as many of the MAS_pb_Clock props).

**Comment by theonegalen** [comment]
Having an additional persistent variable would allow me to not require multiple variations of gauges if I wanted different cockpits to depend on different variables. Having to duplicate literally every prop I use in Warbird Cockpits to enable the battery switch has been a true pain in the butt, and I was hoping to avoid the same annoyance with MAS.

**Comment by theonegalen** [comment]
I understand if you think it is too on the edge of usefulness to do, though.

**Comment by MOARdV** [comment]
> Having an additional persistent variable would allow me to not require multiple variations of gauges if I wanted different cockpits to depend on different variables.

That's a compelling rationale for it.  :)

I think a better implementation is to generalize it - instead of it being a named perisistent, it's an expression (like all other variables).  So, for instance, your case would be

```
powerOnVariable = fc.GetPersistentAsNumber("Warbird_Battery_On")
```

That way, it's not tied strictly to a single persistent, and it can support the full capability of a MAS variable (math expressions, for instance).  So, yeah, I'll see about adding it.

**Comment by MOARdV** [comment]
Okay.  Implemented and working version on [DropBox](https://www.dropbox.com/s/lgffr6rtdf0cc6b/AvionicsSystems-0.14.0b2.zip?dl=0).  Documentation on [the wiki](https://github.com/MOARdV/AvionicsSystems/wiki/MASFlightComputer).

**Comment by theonegalen** [comment]
Thank you so much!
