### ISSUE TITLE
MAS_PAGE IMAGE function.

### ISSUE THREAD

**Issue by DeputyLOL** [MOARdV/AvionicsSystems#15]
Is the 'IMAGE' just supposed to be used an overlay?
Can there be a way to set the position, size and an enabling variable?

**Comment by MOARdV** [comment]
```
IMAGE
{
	name = PFD overlay
	texture = JSI/RasterPropMonitor/Library/Components/NavBall/StaticMask
	//position = 128,256
	//size = 256,256
	//variable = fc.GetBrakes()
	//range = 0.5, 1.1
}
```

Yeah, you can set the position, size, and enabling variable.  (remember that 'range' is not needed if the variable uses <=0 for "off" and >0 for "on")

**Comment by DeputyLOL** [comment]
thank you. The TEXT still doesn't work BTW.

**Comment by MOARdV** [comment]
> The TEXT still doesn't work BTW.

I'm going to need a log, and maybe the configs you're using so I can try it locally.  Text is working for me, so there's got to be something that's being overlooked, or not being reported loudly enough in the log.

**Comment by DeputyLOL** [comment]
Monitor Config: https://www.dropbox.com/s/ud361o9t3iqq3fw/AC_K320_PFD_CAP.cfg?dl=0
Text File: https://www.dropbox.com/s/4yob71gxrlm89of/AC_K320_PFD_TEXT.txt?dl=0
Log: https://www.dropbox.com/s/kykhovycl5cgmkt/KSP.log?dl=0

**Comment by MOARdV** [comment]
As a heads-up, your CrossFeedEnabler and BDAnimationModules plugins are causing problems.  Both throw exceptions at load time.  I'd look at updating or removing them to make sure they're not causing problems.

Are the props and textures referenced in your config file in the released version of your cockpit?  I'd like to get that prop in-game to see if I can figure out why the text is not visible.  Although I also see you're limiting each output to 1 character - I'd try using {0} instead of {0,1:0} for the time being, and maybe put a row of static text up as well, in case the text is drawing off-screen a little bit for some reason

**Comment by DeputyLOL** [comment]
The prop is in the ASET_Prop Pack.
Do you want me to release a dev build?

**Comment by MOARdV** [comment]
I've got the prop pack - although you also have links to textures that are in your cockpit.  A dev build (or even a stripped down "here's what you need for this console" build) would be a little quicker for me to work with.

**Comment by DeputyLOL** [comment]
Put the contents of the zip folder Into the advancedcockpit folder

**Comment by DeputyLOL** [comment]
The monitor on the left is RPM, the one on the right is MAS

**Comment by MOARdV** [comment]
I've checked the IMAGE position, size, and enabling functions, and they're working (for me, at least), so I'm closing this issue out.
