### ISSUE TITLE
Lua-question

### ISSUE THREAD

**Issue by Alexustas** [MOARdV/AvionicsSystems#184]
I plan to make the Event system for automatic switching Standard and Custom Action Groups.

For example, switch AG2 when the altitude is over 65000 m.

So, in order to make the system more flexible and not very difficult to implement, I want to do the following. By using the soft-keys of the CDU I'll set the values of three persistents: 
```

softkey = XXX, fc.SetPersistent("FMS_AG2_EVENT_PARAMETER","fc.Altitude()")
softkey = YYY, fc.SetPersistent("FMS_AG2_EVENT_OPERATOR",">=")
softkey = ZZZ fc.SetPersistent("FMS_AG2_EVENT_VALUE",65000)
```

then I use the LUa function:
```

function AG2_EventTrigger()

	local cond = load("if "..fc.GetPersistent("FMS_AG2_EVENT_PARAMETER")..fc.GetPersistent("FMS_AG2_EVENT_OPERATOR")..fc.GetPersistent("FMS_AG2_EVENT_VALUE").." then return true; else return false; end")

	return cond()	

end
```

This piece of code works fine in  Notepad++ tests, but will it work in the KSP/MAS?

**Comment by Alexustas** [comment]
> Although it may be slow if you call load() every FixedUpdate, because that means recompiling that code every time, even if it does not change. 

my function is just a sketch. The real implementation will be more developed and, I hope, optimized enough

here is the page layout:

![bandicam 2018-07-06 21-50-12-217](https://user-images.githubusercontent.com/6713671/42391041-6609070c-8167-11e8-99fd-7e3fba4f0cc2.jpg)

after adjusting the conditions, the user must save it `(1)`. At this point, a function will be called that compiles the code.
then, the user must make this event active `(2)`, and click the "EXEC" button `(3)` which gives the global permission for the MAS to perform automatic events.

**Comment by MOARdV** [comment]
Very cool!

To answer your original question: No, right now MAS is configured so `load()` does not work.  However, it is very easy for me to change that, and I am trying right now to test it.

**Comment by MOARdV** [comment]
Okay, here is how it can work (very simple example):

```Lua
local function dynamicfunction()
	return 5
end

function MAS_Mfd2_Wrapper()
 return dynamicfunction()
end

function MAS_MFd2_Load()
	local result, errormsg = load("return 3 + 4")
	if result == nil then
-- load returns (function), (error).  If (function) is nil, then (error) has the text of the error.
		fc.LogMessage(errormsg)
	else
		dynamicfunction = result
	end
end
```

with
```
softkey XXX, MAS_MFd2_Load()
TEXT
{
  text = <=0=> $&$ MAS_Mfd2_Wrapper()
}
```
prints "5" until I press the softkey.  Then it prints "7".

`dynamicfunction` is the function that you create at runtime with `load`.  `MAS_Mfd2_Wrapper()` is a function that can be called by the MFD (or other props).

If you replace `MAS_Mfd2_Wrapper` instead of `dynamicfunction`, the text never updates, because the MAS variable does not know that it changed, since the change was inside Lua.

Beta on [DropBox](https://www.dropbox.com/s/qo4a5yxz3qa6065/AvionicsSystems-0.21.0b1.zip?dl=0) so you can experiment with it (all I have tested is the code I showed here).
