### ISSUE TITLE
function 'engine.ToggleThrustReverser()' does not work

### ISSUE THREAD

**Issue by Alexustas** [MOARdV/AvionicsSystems#187]
e.g. `softkey = 1, engine.ToggleThrustReverser()` does nothing

**Comment by theonegalen** [comment]
Shouldn't it be MASThrustReverser in the mm patch instead of JSIThrustReverser?

**Comment by Alexustas** [comment]
since I have both RPM and MAS installed, I just added the module for the MAS to the existing patch

**Comment by theonegalen** [comment]
oh, I see now.

**Comment by MOARdV** [comment]
Actually, it works.  The problem is MOARdV/FlightSystems/Squad.cfg has a MM patch that also adds a MASThrustReverser, so the problem is there are two thrust reversers on the engine.  When you click `engine.ToggleThrustReverser()`, TR No1 starts reversing thrust, and TR No2 immediately switches back to forward thrust.

I will update the MM patch so that it will not add MASThrustReverser if the part already has one.

**Comment by Alexustas** [comment]
oh, that explains everything. Thank you!
