### ISSUE TITLE
Real fuels: monoprop.

### ISSUE THREAD

**Issue by snakeru** [MOARdV/AvionicsSystems#207]
With RealFuels installed the monopropellant gauge stays always at zero (even though the stage propellant is correctly rendered).

**Comment by MOARdV** [comment]
I don't support RealFuels, so if it changes the behavior of monopropellant from stock (such as, whether monoprop can transfer between stages like it does in stock), then it may not work correctly.  I don't really have the time to spend testing mods I don't use normally, so if RF behaves differently than stock, I most likely will not be able to fix this bug.

**Comment by theonegalen** [comment]
I was going to say that you could use a modulemanager script to swap out the monoprop readout with the real fuels equivalent used for RCS fuel. But I think real fuels gives you multiple options for RCS fuel, and I don't believe there's a way for the flight computer to switch the readout on the fly depending on which one you've set up for your particular craft.

I think it would be possible to program it into a Lua script if you knew how to do a Lua script. But I don't know how to do a Lua script yet, and I never use real fuels anyway. There's got to be some way to see mod added resources. I'm going to look at the flight computer.

**Comment by MOARdV** [comment]
MAS iterates over all ModuleRCS (which includes ModuleRCSFX) to create a list of fuels used for RCS.  It will then sum the current and maximum amounts for both.  I know it works with alternate fuels, since I made changes to the algorithm once I started playing with the WBI Flying Saucer, which uses alternate fuels.

If RF uses a module that isn't derived from ModuleRCS, or if the fuel swapping takes place after MAS has scanned the parts, then MAS would have difficulties.  I can dig into the RF code at a later time, but it won't be a top priority - I am trying to avoid adding mod support for mods that I don't use myself, since that means having to reinstall the other mod for testing and debugging purposes.

**Comment by MOARdV** [comment]
I looked at RF and some of the example RF engine mods, and it's not clear to me why RCS modules aren't reporting their fuel type.

Either RF changes ModuleRCS into something that's not derived from ModuleRCS, or it does something with the resources that causes MAS to be unable to get resource info (although that's less likely, since it would mean stock resource tracking would also be broken).  In either case, since I don't want to maintain a Real Fuels development installation in addition to my primary development installation, I'm closing this as a "won't implement".
