### ISSUE TITLE
K.R.A.S.H. is not deactivated on recovery.

### ISSUE THREAD

**Issue by snakeru** [MOARdV/AvionicsSystems#209]
If I click "recover" toggle inside cabin then KRASH keeps running even after I exit to the main menu (i.e. in the main menu with planet and kerbals the words "Simulation running" are still blinking).

**Comment by MOARdV** [comment]
The "Recover" toggle uses a standard KSP function to trigger the recovery sequence.  It's possible that KRASH needs to be somewhat more robust about detecting scene changes (switching from Flight to SpaceCenter in this case).  If there is a trivial change I need to make to notify KRASH, I'll do so.

**Comment by JonnyOThan** [comment]
Is this changed at all from the little orange recovery prop from ASET?  I always have trouble after using that, like menus and buttons don’t work properly.  I know this isn’t that useful, and I will try to investigate deeper.  It’s so much more satisfying to click a recovery prop!

**Comment by theonegalen** [comment]
I believe the recovery prop on RPM has to be switched to a specific frequency, like the aset radio nav functions. It worked for the one time I tried to use it.

**Comment by MOARdV** [comment]
All MAS does is trigger the stock event `GameEvents.OnVesselRecoveryRequested.Fire(vessel)`, where `vessel` is your current vessel.  That's the same thing RPM does.  If KRASH doesn't watch for this event, then I can see it being a problem.  It might be a question of figuring out what assumptions the KRASH mod uses.  Since it's not a mod I use, it won't have a high priority for me at the moment.

**Comment by MOARdV** [comment]
> I haven't dug at the code or done any scientific testing of repro cases, but OnVesselRecoveryRequested sounds like a callback that the game fires to any listeners when recovery is requested. But there might be additional logic that needs to run..

The ShipConstruction entry point does sound like it's a better match.  If that works (both with and without KRASH installed), MAS can switch over to using it.

**Comment by JonnyOThan** [comment]
OK, spent some time investigating this one.

I was not able to easily repro the issues I had seen while playing naturally and using the recover prop.

The KRASH simulation issue is tricky.  KRASH does not allow you to recover the ship after it has landed.  It achieves this by disabling the GUI button, so naturally it does not try to respond at all to recover events.  That aspect of this issue is probably on the KRASH side - if some other mod manages to trigger recovery, KRASH needs to handle it.  On the other hand, it might make sense for RPM/MAS to disable the recovery button if it can detect that some other mod has disabled the normal Recover Vessel GUI button.  For reference, the commit that disables the button in KRASH is [here](https://github.com/linuxgurugamer/KRASH/commit/f1d8111d78c1fd293d809ac3a3649d8c12f52a50)

**Comment by MOARdV** [comment]
I've rejected the pull request.  As I stated, I am not willing to add special-case handling for an uncommon corner case (one specific mod that hijacks KSP UI behavior).  If KRASH doesn't pay attention to callbacks that notify it that scene changes or vessel recovery are taking place, that's something that that mod should address.

I especially don't want to have to scan the entire GameObjects database every FixedUpdate to see if a specific UI component exists while a vessel is landed - that impacts every player that's on the ground (spaceplane taxiing, lander / rovers. etc) regardless of whether KRASH is installed.

I think a better approach is to write a bridge DLL (something similar to DPAI_RPM.dll or SCANsatRPM.dll) that is linked against KRASH.  The bridge DLL can provide an alternate method to poll if the vessel is recoverable, and it can have a method to recover the vessel.  A Module Manager patch could be used to update the props that use the built-in MAS methods with calls to the bridge DLL's methods.

**Comment by JonnyOThan** [comment]
I think a bridge DLL is a bit overkill for something this simple.  But I totally understand the performance concern. If there’s an easy and fast way for the recovery prop to figure out if recovery should be disabled, I think it makes sense to do that.  A better fix for this specific issue would probably be for krash to terminate the simulation on recovery, but maybe there’s some good reason why that is hard or impossible. Just speculating here, but terminating the simulation is essentially loading a quick save, and maybe you can’t do that from the recovery handler.

In any case, we do need to change the function that gets called when the recovery prop is clicked. My initial hunch was that krash was broken for the same reason KSP gets broken but that turned out to be wrong. I’ll open a separate issue because they’re not actually related.

**Comment by MOARdV** [comment]
Closing this issue, since it seems to be an interaction with specific mods.  Barring a clear fix that doesn't impose an excessive workaround in MAS, I don't see any changes outside of investigating the use of ShipConstruction.RecoverVesselFromFlight() in lieu of the existing recovery code path.
