### ISSUE TITLE
Gael map for the globe instrument.

### ISSUE THREAD

**Issue by snakeru** [MOARdV/AvionicsSystems#210]
It would be nice to have Gael map if GPP is installed. The map is attached.
![map-kerbin-sat](https://user-images.githubusercontent.com/72657/49318747-12d8ce80-f4fa-11e8-93b3-69db6257324e.png)

**Comment by MOARdV** [comment]
I will need to figure out what the correct Module Manager patches are to incorporate this map into the IMP/Globus and MFDs

**Comment by MOARdV** [comment]
> Maybe something like

I think it'd be slightly easier - you wouldn't need to erase the existing MODEL.  You would only need to add the textures to the existing model using `@MODEL`.  What I don't remember from the MODEL syntax is whether you can replace only one texture using the `texture = ` syntax, or if you have to list all of them (even if you're not pointing them somewhere else).

MFD pages would be a little more involved, since you'd need to scan all the MAS_PAGE nodes for IMAGE nodes containing `texture = path to Kerbin texture` and update only those nodes.  I know it's possible with current MM syntax, but it's something I haven't done myself.

**Comment by theonegalen** [comment]
I don't remember ever having much success just removing and replacing a single texture, I always just the model node entirely.

**Comment by MOARdV** [comment]
Sorry this took so long - I spent a lot of time trying to figure out how to replace the Kerbin map in all of the MFD pages.

I've got a test for the Gael replacement map on [DropBox](https://www.dropbox.com/s/fsief67kkdwj4yz/GPP_IMP.zip?dl=0).  All this does is update the IMP - writing a patch that can update MFDs is way more Module Manager complexity than I want to tackle.  The ZIP contains the patch and map stored so you can unzip it over the GameData folder.

I've tested it locally to make sure the underlying patch works (the IMP is updated), but I don't have GPP installed to make sure the NEEDS[GPP] enables correctly.  If I can get feedback from someone playing on Gael, I'd appreciate it.

One bit of feedback on the Gael map - it does not have latitude and longitude lines on it like the Kerbin map does, so there's no visual feedback of position on the globe.  It's not a big deal, but it is a difference.

**Comment by snakeru** [comment]
Sorry, now this took long for me to verify. The patch works. I do not know how prominent the grid lines on the Kerbin map are so please tell me if I need to make them darker.

![image](https://user-images.githubusercontent.com/72657/56560882-ed7e5700-65a5-11e9-92ca-d66ac7b4d743.png)
![image](https://user-images.githubusercontent.com/72657/56560895-f4a56500-65a5-11e9-8bf8-cb7149a535c7.png)

**Comment by snakeru** [comment]
In case github does something to the PNG: The size is 633274 bytes and MD5 is d18d1fac83c726894c6ea3c1e83c5881

**Comment by MOARdV** [comment]
I think those lines are fine - they're visible, but they're not overbearing.  Thank you for updating (and testing) it.
