### ISSUE TITLE
DSKY Rendez-vous seems to be broken.

### ISSUE THREAD

**Issue by snakeru** [MOARdV/AvionicsSystems#222]
I have filed this issue in the forum thread. Re-posting here just for the tracking purposes.

I have tried making an orbital rendezvous and DSKY reports no info (all minuses). The screenshot features MAS 0.90.0.
<img width="890" alt="screenshot-20180812-185531" src="https://user-images.githubusercontent.com/72657/50738227-d6bc1c00-11d1-11e9-8bef-c1e617d838b3.png">

**Comment by MOARdV** [comment]
It has been a long time since I worked on the DSKY.  I remember that it was incomplete when I got busy working on other things, and I think you found what I did not complete.

I would have to review alexustas' original DSKY to remember exactly what the top row RNDZ button should display.  I think it was closest approach data, but I could be mistaken.

The middle row RNDZ button should display time to closest approach, but I can see in the Lua script that it's not implemented (I think that should be an easy one for me to implement, since MAS already has those features).

The bottom row RNDZ button I believe would show delta-V required to start a Hohmann transfer orbit to the target.  Again, MAS has that information available, but the script does not currently implement it.

So, I think it should be easy to fix 2/3 of the missing functionality, and only a little bit more work for the remaining 1/3.  Thank you for the reminder that I need to finish the instrument.

**Comment by MOARdV** [comment]
Done.  Documentation of intended behavior is [over here](https://github.com/MOARdV/MOARdVPlus/wiki/How-to-DSKY).

**Comment by theonegalen** [comment]
You're really cleaning up today!

**Comment by MOARdV** [comment]
> You're really cleaning up today!

Yeah.  I'm pushing the "release before 1.0" this weekend, along with a mod that showcases the more advanced IVA tricks that MAS allows (hiding [over here](https://github.com/MOARdV/MOARdVPlus)).

**Comment by snakeru** [comment]
@MOARdV I have have a feature request then.
I tried to implement a science controls instrument about a week ago but quickly realized, that
(1) I have no idea, how to do that and
(2) existing instruments cfg files seem to only configurations for instruments that already exists, which confuses me.

Basically, I expected that I'll be able to group relative switches, toggles, colliders, etc in a cfg file and specify their relative positions and then later on be able to include the whole group as a single instrument. However, that might be just not how Unity works.

I now start to suspect that .mu files hide the configuration I need which means I won't be able to do that (I only have text editor).

**Comment by theonegalen** [comment]
> Yeah. I'm pushing the "release before 1.0" this weekend, along with a mod that showcases the more advanced IVA tricks that MAS allows (hiding [over here](https://github.com/MOARdV/MOARdVPlus)).

ooooooh. This might be the one thing that is going to get me to download BDB. It's just so big, and my RAM is so small. :D

**Comment by MOARdV** [comment]
@snakeru :
> Basically, I expected that I'll be able to group together switches, toggles, colliders, etc in a cfg file and specify their relative positions and then later on be able to include the whole group as a single instrument. However, that might be just not how Unity works.

You can mix & match props using MODEL nodes like other KSP models (that is how the modular switches work).  The problem occurs if active components (colliders, transforms for animations) are duplicated.

> BDB. It's just so big, and my RAM is so small

It's a huge mod.  I have it cut down to just the Apollo, Saturn, and a few odds-and-ends (separatrons, launch clamps).
