### ISSUE TITLE
Support IVA switching

### ISSUE THREAD

**Issue by MOARdV** [MOARdV/AvionicsSystems#248]
Probably as a separate DLL, so it can be separated from the core MAS distribution (for people on RPM, or other uses).  Electrocutor on the forum has/had a plugin KSPF that had IVA switching.  I will check into it as a bootstrap and see if the license is compatible with the MIT License, or if I'll need to try to invent it myself.

Bonus if the plugin can also extend the upgrade system to allow IVA variants to unlock.

**Comment by MOARdV** [comment]
So I don't lose track of this info: [KSPF](https://forum.kerbalspaceprogram.com/index.php?/topic/168795-electrocutors-thread/), also starred on wiki, has the relevant code; MIT license, so it's the same as MAS.  I should see if I can find a way to make the MAS code work with KSPF if the latter is installed.

**Comment by theonegalen** [comment]
KSPF is great. What it doesn't do is allow for additional IVA variants to be unlocked as the player progresses through the tech tree. Unlocking more advanced instruments as the player proceeds through the game still requires using additional parts.

**Comment by theonegalen** [comment]
I just tested this in 1.10.1. KSPF threw a nullref. I assume it did because of differences in the KSP code post 1.8 and the switchover to Unity 2019.

`[ERR 19:53:43.077] Module ModulePartData threw during OnLoad: System.NullReferenceException: Object reference not set to an instance of an object
  at AvailablePart..ctor (AvailablePart ap) [0x00023] in <c1858a3f77504bd1aaa946fdccf84670>:0 
  at KSPF.Parts.PartModules.ModulePartData.OnLoad (ConfigNode node) [0x0000d] in <06501830a23e4f87b100711e84f16e57>:0 
  at PartModule.Load (ConfigNode node) [0x001ab] in <c1858a3f77504bd1aaa946fdccf84670>:0 `

It does, however, work as expected in 1.7.3.

**Comment by MOARdV** [comment]
This is mooted by https://forum.kerbalspaceprogram.com/index.php?/topic/206744-112x-reviva-the-iva-revival-and-editorflight-switcher-073-12th-apr-2022/

No sense reinventing the wheel.
