### ISSUE TITLE
Stock dV Stats

### ISSUE THREAD

**Issue by Alexustas** [MOARdV/AvionicsSystems#254]
Can you add the values of the dV calculations (stage and total), which provides the game itself, as a separate fc-functions?
Since KSP, MechJeb and KE returns slightly different readings of dV, I want to give players the opportunity to choose the source of data

**Comment by MOARdV** [comment]
`DeltaVStage()` and `DeltaVStageMax()` is always a MAS computation, never stock, KE, or MechJeb.

Total dV `DeltaV()` is never MAS, because it is more complicated.  It is always KE, MechJeb, or stock.

I can add functions for stock-only `DeltaV()` and `DeltaVStage()`, but stock does not report `DeltaVStageMax()`, so I would have to compute it using stock information, if it gives me all of the information I require..
