### ISSUE TITLE
Different SCANsat map aspect ratios on the same monitor

### ISSUE THREAD

**Issue by Alexustas** [MOARdV/AvionicsSystems#257]
I ran into such a problem. 
On some MFD pages I already use a full rectangular SCANsat map with a 2:1 aspect ratio. But on other pages I need square map with a 1:1 aspect ratio. 
for a rectangular map I have to use `zoomModifier = 1` and for the square map I have to use `zoomModifier = 2` . But this parameter is specified in the **monitor** config, not the page config, and it is set only once per monitor. Thus, if the map is rendered correctly in a rectangular representation, it is distorted in square and vice versa.

![screenshot95](https://user-images.githubusercontent.com/6713671/53443434-858c1400-3a2d-11e9-8533-3d0259101c09.png)

![screenshot94](https://user-images.githubusercontent.com/6713671/53443436-88870480-3a2d-11e9-892a-61e9b162d9f9.png)

**Comment by MOARdV** [comment]
The problem is SCANsat only understands one aspect ratio - I do not think I can change it for every page without the update becoming very slow.

However, Unity allows me to blit from the source to the destination using UV scale and UV offset, so maybe the solution is:

I will add options to change the scale and offset in RPM_MODULE.  This allows SCANsat to be configured with one aspect ratio, and RPM_MODULE can copy only part of the data for the aspect ratio that is different.

**Comment by MOARdV** [comment]
I think the easiest fix is to allow `renderSize` and `size` to have different aspect ratios.  If they are different aspect ratios, MAS will crop and center the image from the plugin.

**Comment by MOARdV** [comment]
In your example above,
top image (2:1 aspect ratio) will use
```
RPM_MODULE
{
  renderSize = x, x // x is the size of the render texture for reading from SCANsat
  size = x, y // y = 1/2 x.
}
```

For example, `renderSize = 512, 512` and `size = 512, 256`.

MAS will crop and center the image.  You can also use `renderSize = 256, 256` and `size = 512, 256`.
