### ISSUE TITLE
Triggering an action in lua?

### ISSUE THREAD

**Issue by DeputyLOL** [MOARdV/AvionicsSystems#31]
Sorry to have to keep asking. Is there anyway to trigger something like 'far.IncreaseFlapSetting()' in lua?
While im here, do you know whats wrong with this?
PROP
{
    name = AC_K320_Control_FlapsCtrl

```
MODEL
{
    model = ASET/ASET_Avionics/ModernPack/ASET_FlapsCtrl/ASET_FlapsCtrl
    texture = ASET_FlapsCtrlDiffuse,ASET/ASET_Avionics/ModernPack/ASET_FlapsCtrl/ASET_FlapsCtrlDiffuse
}

MODULE
{
    name = MASComponent
    COLLIDER_EVENT
    {
        name = PLUS
        collider = FlapsLeverUP_collObj
        onClick = fc.AddPersistentClamped("AC_A320_FlapLever",1,0,3)
    }

    COLLIDER_EVENT
    {
        name = MINUS
        collider = FlapsLeverDown_collObj
        onClick = fc.AddPersistentClamped("AC_A320_FlapLever",-1,0,3)
    }

    ROTATION
    {
        name = Lever position
        transform = FlapsLeverLoc
        variable = fc.GetPersistent("AC_A320_FlapLever")
        startRotation = 0,0,0 
        endRotation = 21,0,0
        range = 0.0,3.0
        blend = true
        speed = 10.0
    }

    AUDIO_PLAYER
    {
        name = Clicker
        sound = ASET/ASET_Avionics/ModernPack/Sounds/FlapsClick01
        volume = 1.0
        trigger = BOTH
        variable = fc.GetPersistent("AC_A320_FlapLever")
        range = 0.5,1.5
    }

    AUDIO_PLAYER
    {
        name = Clicker
        sound = ASET/ASET_Avionics/ModernPack/Sounds/FlapsClick01
        volume = 1.0
        trigger = BOTH
        variable = fc.GetPersistent("AC_A320_FlapLever")
        range = 2.5,3.5
    }
}
```

}

This stops the database from reloading and throws this:

[LOG 17:05:33.088] PartLoader: Compiling Internal Prop 'AdvancedCockpit/K320/Control_FlapLever/AC_K320_Control_FlapsCtrl'
[EXC 17:05:33.093] NullReferenceException: Object reference not set to an instance of an object
    PartLoader.ReplaceTextures (UnityEngine.GameObject model, System.Collections.Generic.List`1 textureNames, System.Collections.Generic.List`1 newTextures)
    PartLoader.CompileModel (.UrlConfig cfg, .ConfigNode partCfg, Single scaleFactor, .AvailablePart partInfo)
    PartLoader.LoadInternalProp (.UrlConfig urlConf)
    PartLoader+<CompileInternalProps>c__Iterator4B.MoveNext ()

It's very likely that I will have more questions in the future, would you prefer for me to open seperate issues for each question or put all my questions in one issue?

**Comment by MOARdV** [comment]
One thread for questions is fine.  If it gets too cluttered, we can move to a new one.

The error is in the MODEL node.  It's an exception that's thrown when there's an invalid `texture =` line (I can't tell you why it failed - it may be hinted at where KSP loads textures).  Try simply commenting out the `texture =` line.

As for the MASComponent - what I would do is replace `fc.AddPersistentClamped("AC_A320_FlapLever",1,0,3)` with `far.IncreaseFlapSetting()`, and do similarly for the 'decrease' flap collider.  You can then replace all of the `fc.GetPersistent()` calls with `far.GetFlapSetting()`.

Otherwise you will also need to use a custom Lua script that will query the persistent and set the flap setting that replaces for `fc.GetPersistent()` - but that's a lot of extra overhead that you should avoid if it's not essential for something.

**Comment by DeputyLOL** [comment]
Ok, I might use the flap lever to directly control the flaps for now. I wanted to be able to allow flap movements only when certain variables are in range.

**Comment by MOARdV** [comment]
> Ok, I might use the flap lever to directly control the flaps for now. I wanted to be able to allow flap movements only when certain variables are in range.

Ah.  In that case, instead of `fc.AddPersistentClamped(blah, blah, blah, blah)` use `DL_IncreaseFlapsIfPermitted()` in your custom Lua script file:

```Lua
function DL_IncreaseFlapsIfPermitted()
  if fc.GetPersistentAsNumber("AllowFlapChanges") > 0 then
    far.IncreaseFlapSetting()
  end
end
```

Even though it's a script, it's only executed when you click on the collider, so the cost is a one-time thing, not something that happens continuously.  Do the same thing for the 'decrease flaps' option.  I'd still use the `far.GetFlapSetting()` to indicate flap positions, unless you also want to suppress that information.

Also, [Wall-O-Text](https://github.com/MOARdV/AvionicsSystems/wiki/Lua-Scripting-Example) scripting.

**Comment by Alexustas** [comment]
for clarity. to automatically start some action, I can use the Lua script or do I need something like RPM EVENT?

for example, for capsules "ALCOR" I have long been want to realize the automatic engine cut-off at the touch of the surface, ie it should happen automatically when certain conditions are met, not by clicking on the button.

**Comment by DeputyLOL** [comment]
You could do that in RPM using triggers,  i think using the function above would allow automatic functions.

**Comment by Alexustas** [comment]
> something like RPM EVENT?

Of course I meant  "RPM_TRIGGERED_EVENT". I'm sorry for the confusion

**Comment by Alexustas** [comment]
that is, the following script will work?

```
function myAutoCutoffFunction()
    if bla-bla-bla then
        fc.ToggleEnginesEnabled()
    end
end
```

**Comment by DeputyLOL** [comment]
it should do.

**Comment by MOARdV** [comment]
> that is, the following script will work?

Yes ... with a couple of changes.  The function I posted earlier works as a Collider action - it only fires if the player hits the collider.  If you want something that is running "automatically", it needs to be a variable (meaning it is in a MASComponent: `variable = myAutoCutoffFunction()`

Then take your function

```Lua
function myAutoCutoffFunction()
    if bla-bla-bla then
        fc.ToggleEnginesEnabled()
    end

  return 1
end
```

The variable `myAutoCutoffFunction()` gets checked every update, so the `if bla-bla-blah` test will happen every update.  As I wrote it, it doesn't do anything else, since it always returns 1.  But you could have it return 1 or 0 to indicate if the auto cutoff function is enabled (for an indicator lamp, for example):

```Lua
function myAutoCutoffFunction()
    local cutoffEnabled = fc.GetPersistentAsNumber("bla-bla-bla")
    if cutoffEnabled > 0 then
        if fc.VesselLanded() > 0 and fc.GetEnginesEnabled() > 0 then
            fc.ToggleEnginesEnabled()
        end
    end

  return cutoffEnabled
end
```

Should there be a `fc.SetEnginesEnabled()` that can have `true` or `false`?  That would allow `fc.SetEnginesEnabled(false)`, so the engines can't automatically flip on and off.

**Comment by DeputyLOL** [comment]
Would it be possible to have a momentary contact collider?
i have this and its not working, im not sure whats wrong with it.

function ACK320FlapControl()
	if fc.GetPersistent("AC_A320_FlapLever") > far.GetFlapSetting() then
		far.IncreaseFlapSetting()
		return 1 -- This is only here for debugging purposes
	elseif fc.GetPersistent("AC_A320_FlapLever") < far.GetFlapSetting() then
		far.DecreaseFlapSetting()
		return -1 -- This is only here for debugging purposes
	else
		return 0 -- This is only here for debugging purposes
	end
end

**Comment by MOARdV** [comment]
> Would it be possible to have a momentary contact collider?

Already there.  Colliders have an `onClick` and `onRelease` (that's how the number pad LEDs on the MechJeb panel in my Yarbrough sample IVA work).  And the `onClick` can be set up as a repeating event, which is how the dimmer switches work.
