### ISSUE TITLE
Nav radio functions issue

### ISSUE THREAD

**Issue by vulkans22** [MOARdV/AvionicsSystems#325]
This was a fun one to track down... While converting the various ASET radio props, I found most of the functions related to radio navigation (eg: GetNavAidType(), GetNavAidIdentifier()) were all returning their false values regardless of whether a correct frequency was present in NavRadio.frequency. After much hunting I've reached the conclusion that:

1. The affected functions were all calling NavAidInRange() from an if conditional, which was incorrectly coming back as false.
2. NavAidInRange() depends on slantDistance for its calculations, which was being defined as -1 no matter what, and thus NavAidInRange() was always returning false.
3. That calculation depends on beacon.maximumRange, which was coming back as 0.
4. Beacon.maximumRange is calculated by UpdateHorizonDistance()
5. Which is called from a for loop in ApplyChanges(), MASSettings.cs:202
6. Which is only ever called by pressing the "Ok" button on the AppLauncher MAS window (MASSettings.cs:163).

Hence, the majority of Nav radio functions will only work correctly when the Ok button is pressed before launching a vessel, otherwise they will all return as false.

Suggest breaking off MASSettings:201-206 into its own wee function and calling it after MASLoader:LoadAssets() has done its thing.

**Comment by MOARdV** [comment]
That makes sense - I think the last time I tested radio nav was back before I had changed MAS so it wouldn't automatically add waypoints for each nav beacon, since that cluttered things up pretty badly.

**Comment by MOARdV** [comment]
I was a little too clever designing that code (and forgetting what I did).  The range update can't be done by MASLoader::LoadAssets(), because MASConfig hasn't been invoked yet.  The solution was moving the update loop out of MASSettings and into MASLoader, and calling it from both MASSettings (if the player presses OK), and into MASConfig once it has finished parsing its ConfigNode.

I'm going to try to kick an update out "soon", once I take a cursory look at MAS in KSP 1.11.0.
