### ISSUE TITLE
MAS MONITOR / Text node character alignment

### ISSUE THREAD

**Issue by Alexustas** [MOARdV/AvionicsSystems#65]
![bandicam 2017-10-31 19-06-28-618](https://user-images.githubusercontent.com/6713671/32228913-6411cf88-be71-11e7-9f70-d8b608fd2af6.jpg) 
![bandicam 2017-10-31 19-06-44-500](https://user-images.githubusercontent.com/6713671/32228921-67f578ac-be71-11e7-874d-9d0192932532.jpg)

Now the characters are aligned to the bottom edge of the letter "box".

Is it possible to align the symbols with the vertical center of the "box"?
Like here:

![bandicam 2017-10-31 19-11-52-281](https://user-images.githubusercontent.com/6713671/32229092-d6945ab2-be71-11e7-82e1-9c20c6b57780.jpg)

**Comment by MOARdV** [comment]
Hmm.  It looks like I added text alignment for prop labels, but not for the monitor.  I think this will be easy to add.

**Comment by MOARdV** [comment]
Oh - one difficulty with this.  The text anchor is upper-left.  If I added middle-left, the text will not be moved into the middle of the bounding box. It will be moved much farther up, so that it is partially in the box above it.  So text anchor is not the right thing to change.

Right now, the text is positioned based on the fixed line spacing (for example, fontSize 8,16 has the first row of text at y=16 on the screen.  I think I need to change how I place the initial line based on text metrics.

**Comment by MOARdV** [comment]
I understand what the problem was.  I did not account for the font "ascent" when I originally wrote this, so the characters were drawn too far down in the box.  That has been corrected in the new beta on [DropBox](https://www.dropbox.com/s/vrfi9xd0bg3kuyb/AvionicsSystems-0.10.0b1.zip?dl=0).

The characters are drawn on the baseline.  They are not perfectly centered in the box, since there needs to be room for the descenders below the baseline (such as letter 'y'), but they should all fit in their box correctly now.

**Comment by Alexustas** [comment]
It's much better!

that's how it was before

![bandicam 2017-11-05 04-13-19-975](https://user-images.githubusercontent.com/6713671/32410362-e78d55e6-c1df-11e7-95dc-9ed715d5bb92.jpg)

and now

![bandicam 2017-11-05 04-09-03-470](https://user-images.githubusercontent.com/6713671/32410342-6be03c92-c1df-11e7-85e3-06c7c9b44d86.jpg)

Thank you!
