### ISSUE TITLE
MAS MONITOR / Text node font size

### ISSUE THREAD

**Issue by Alexustas** [MOARdV/AvionicsSystems#66]
I have monitor 1024x1024 px, char size 16x32.

1. If I set `fontSize = 8, 16` I get this:

![bandicam 2017-10-31 19-22-49-731](https://user-images.githubusercontent.com/6713671/32229306-540567c0-be72-11e7-8be9-4f19628cd8bd.jpg)
![bandicam 2017-10-31 19-43-34-712](https://user-images.githubusercontent.com/6713671/32229978-e2df5a04-be73-11e7-8a04-2c22eb205284.jpg)

The total dimentions of the text-block is exact a half of normal size, but the size of the characters themselves is not a half of the normal size (at least character **height**)

2. If I set `fontSize = 32, 64` I get this:

![bandicam 2017-10-31 19-20-50-183](https://user-images.githubusercontent.com/6713671/32229523-d383355e-be72-11e7-95c8-b92584d9ac26.jpg)

I really really need this feature, because my new MFD design uses it quite often

![mfd_v3](https://user-images.githubusercontent.com/6713671/32230343-c2c32ec0-be74-11e7-94db-78d8c57d4b45.png)

**Comment by Alexustas** [comment]
and another issue with characters size :

![bandicam 2017-10-31 23-48-37-171](https://user-images.githubusercontent.com/6713671/32243069-411204ba-be96-11e7-9557-a65d1953e0d6.jpg)

font - Arial, fontSize = 16,32

**Comment by MOARdV** [comment]
Okay, I have a font size fix almost ready.  I want to get your opinion on one thing before I commit the change.

If, in MASMonitor:
```
fontSize = 16, 32
```

and in a page:
```
TEXT
{
  text = This is text
  fontSize = 8, 16
  position = 0, 2
}
```
Should "position" be 2 lines of size 16, or 2 lines of size 32 (default text size)?

**Comment by Alexustas** [comment]
> Should "position" be 2 lines of size 16, or 2 lines of size 32 (default text size)?

I believe that the default size is better. but I just guess and I'm not completely sure.

**Comment by MOARdV** [comment]
> I believe that the default size is better. but I just guess and I'm not completely sure.

Okay.  I will use default size.  It is easy to change, and I don't know which is better.

**Comment by MOARdV** [comment]
This is 95% fixed in the new beta on [DropBox](https://www.dropbox.com/s/vrfi9xd0bg3kuyb/AvionicsSystems-0.10.0b1.zip?dl=0).

I will need to do some additional work to make it 100% - the remaining problem is some fonts (such as Arial) have a line-to-line spacing that is not the same as the font size, and the descender on some characters go too far down (for instance, the Arial 'y' letter).  I fix that by pushing the bottom upwards, but that means the letter is not sitting on the font baseline (see the word 'Systems' with dotten line below).

![fontimprovement](https://user-images.githubusercontent.com/6089493/32410076-7c98553c-c186-11e7-9f6e-2298f714bc30.png)

I will keep this issue open until I fix that last little bit, but I think this is much better now.

**Comment by Alexustas** [comment]
Excellent!

![bandicam 2017-11-05 04-09-31-742](https://user-images.githubusercontent.com/6713671/32410382-34e2259c-c1e0-11e7-86d8-b73bd230c8cf.jpg)
![bandicam 2017-11-05 04-09-41-276](https://user-images.githubusercontent.com/6713671/32410383-390521e2-c1e0-11e7-94af-ca8c26c1480b.jpg)
![bandicam 2017-11-05 04-09-52-949](https://user-images.githubusercontent.com/6713671/32410384-3b6daecc-c1e0-11e7-8384-6a6df58790a3.jpg)
![bandicam 2017-11-05 04-10-18-590](https://user-images.githubusercontent.com/6713671/32410385-3caecf78-c1e0-11e7-85d0-0702fdfd47d5.jpg)

**Comment by MOARdV** [comment]
Last part of the fix is complete.
