### ISSUE TITLE
"MASCamera" improvement

### ISSUE THREAD

**Issue by Alexustas** [MOARdV/AvionicsSystems#71]
**FPS**

Is it possible to make an image update not every game frame, but every Nth frame?
By default this attribute is 1, but in order to simulate processing or communication delay for a certain camera type (part) we had the opportunity to change this parameter

 **CAMERA RESOLUTION**

There is quite simple and clear. The ability to limit the resolution of an image, regardless of the monitor

**SHADERS per camera model**

Is it possible to make configuring camera shaders in the "MASCamera" config but not in the "Monitor"? Different models of cameras have different shaders and we can select these shaders using a monitor or some control panel. So, if we switched on the "night vision" mode on one monitor, we'll see this on other monitors that show the same image. 
On the other hand, if a particular camera model (part) only has a bad black-and-white mode, we can not get a full-color Full HD picture from it, regardless of the monitors and everything else

In the ideal case all these parameters must be grouped into a preset. 
let's say this camera has two modes: 1. High-res color image, 2. Low-res noisy "night vision" .
Or 1. Low-res b/w real-time, 2. High-res full-color but low FPS .

**Applying "Pan" and "TIlt" onto a camera model.** 

 If the camera model (part) has a panoramic head on its mount, we can specify the appropriate transforms for each axis and animate them according to the values of Pan and Tilt for a particular camera. 
 For what I need it.
I have long time  wanted to make a camera with a built-in searchlight )

And the last (at least for now : ) )

**Deployment Animation**

Toggle a specified animation depending on the value of the specified variable.
If the model of the camera has a folding boom-extension. We can hide it under the fairing during launch, and when we are on orbit, deploy it and get the better viewpoint

**Comment by MOARdV** [comment]
> FPS

If it is for MASCamera, this is easy.  Probably also easy for CAMERA in MASMonitor.

> CAMERA RESOLUTION

Right now, all cameras are 512 x 512.  It is easy to change this in MASCamera.

> SHADERS per camera model

This is tricky.  The variables in a shader are updated using the MASFlightComputer, but the camera model is on a different part.  If the player is in Pod A and uses the camera, the variables will be attached to Pod A.  If the player then switches to Pod B (for example, CSM to LEM), then the variables will stop updating because the Pod A flight computer goes to sleep.  Even worse if the pods undock.

I will have to think about this.  I agree that it is the better way to apply camera effects, but I am not sure yet how that will work.

> Applying "Pan" and "TIlt" onto a camera model.

RPM allowed external part animation.  I think I can add something to MASCamera so it can control transforms on axis.  A camera with a searchlight would be a very cool part.

> Deployment Animation

KSP has a ModuleDepolyablePart modules, such as ModuleDeployableAntenna.  I think maybe I can make a ModuleDeployableCamera that can control animation using the KSP modules.  That also allows the camera to break if it is deployed while flying too fast.

I think the only difficult part of the request is the SHADERS per camera module.  It is a good idea.  I need to think about how I can make it work, and I need to think about what happens if the camera has a shader, and the CAMERA node on the page also has a shader.

**Comment by Alexustas** [comment]
> RPM allowed external part animation. I think I can add something to MASCamera so it can control transforms on axis. A camera with a searchlight would be a very cool part

for clarity,  first of all I meant camera as a separate part, not a part of cabin model

**Comment by MOARdV** [comment]
> for clarity, first of all I meant camera as a separate part, not a part of cabin model

Yes.  I think maybe MASCamera can have `panTransform` and `tiltTransform`, and it will find those transforms on the same part as MASCamera.

**Comment by Alexustas** [comment]
I think you can add the option "use camera axes," then specify the names of the transforms and local (X,Y or Z) axis of that taransform for each axis and then apply Pan and Tilt parameter to them.
It is assumed that the camera's transform is a child to the Tilt axes and Tilt is a child to the Pan

And in case this camera model (3D-model) does not have suitable axes, we use the old way and apply Pan and Tilt to the camera's transform.

![cam](https://user-images.githubusercontent.com/6713671/32627538-9b0df288-c5b4-11e7-8e02-47711835ced2.png)

**Comment by MOARdV** [comment]
Oh, yeah.  I did not think that through.  If there is a tilt transform, I do not want to change the tilt on the camera transform if that transform is a child of the tilt transform - that would cause double tilt.

You want to specify the axis for each transform?  So, 'tiltTransform = aTransformName,x', for example to say "tilt = rotate 'aTransformName' around X axis"

**Comment by Alexustas** [comment]
Alternatively, declare a conventional rule that only one axis is used, for example, only 'X' axis.
And model makers must follow this rule.

**Comment by MOARdV** [comment]
So I can keep track of what I'm doing :)

- [ ] FPS
- [ ] Camera resolution
- [ ] Shaders per camera
- [ ] Camera Model pan/tilt
- [ ] Deployment animation
- [ ] Multiple shader / resolution per camera

**Comment by InsaneDruid** [comment]
MasCameras Fov should not be clamped to a maximum of 90 degrees but to a rnge of maybe 0-180°, as max 90° renders wide-angle cams impossible to implement, for example the fisheye ring in all russian VZORs.

**Comment by MOARdV** [comment]
> MasCameras Fov should not be clamped to a maximum of 90 degrees but to a range of maybe 0-180°

I can expand the range to 1-179°.  0 and 180 are not possible due to math errors that can crop up.

**Comment by MOARdV** [comment]
@Alexustas - do you have a camera model with pan and rotate transforms?  A rough model that is only for testing is okay.  Or does the ASET exterior camera have transforms already?

**Comment by MOARdV** [comment]
New Beta on [DropBox](https://www.dropbox.com/s/cjyesnaluddk9g7/AvionicsSystems-0.12.0b2.zip?dl=0).

`shaders`, `properties`, and `texture` are no longer part of the CAMERA node in a page.  Instead, they belong in a [MODE](https://github.com/MOARdV/AvionicsSystems/wiki/MASCamera#camera-modes) field in the MASCamera.  More than one MODE may be included, and there are new functions in `fc` to select them.  The MODE is optional for MASCamera - if there are no MODE settings, the camera defaults to a color camera with no post-processing effects.

**Comment by Alexustas** [comment]
> @Alexustas - do you have a camera model with pan and rotate transforms? A rough model that is only for testing is okay. 

very quick and rough model here:
https://www.dropbox.com/s/sj5h90t2je3qcn6/ASET_MAS_Camera.zip?dl=0


![bandicam 2018-01-22 15-23-05-400](https://user-images.githubusercontent.com/6713671/35216212-b06d5c32-ff88-11e7-8186-5afed01c533c.jpg)

![bandicam 2018-01-22 15-15-02-850](https://user-images.githubusercontent.com/6713671/35216224-b66e0190-ff88-11e7-83cb-1f69e7568881.jpg)

![bandicam 2018-01-22 15-14-39-968](https://user-images.githubusercontent.com/6713671/35216234-bcdd779a-ff88-11e7-95ac-2e4153429b27.jpg)


sorry for the lack of response, I'm very busy recently.

**Comment by MOARdV** [comment]
> sorry for the lack of response, I'm very busy recently.

That is okay.  Work is becoming very busy for me, so I want to finish some difficult MAS changes while I have time.

`panTransformName` and `tiltTransformName` now available for MASCamera on [DropBox](https://www.dropbox.com/s/cjyesnaluddk9g7/AvionicsSystems-0.12.0b2.zip?dl=0).

**Comment by MOARdV** [comment]
Will update documentation soon, but:

* `fc.GetCameraDeployable(index)`
* `fc.GetCameraDeployed(index)`
* `fc.GetCameraDamaged(index)`
* `fc.GetCameraMoving(index)`
* `fc.ToggleCameraDeployment(index)`

Plus a new part module MASDeployableCamera, which controls deploying / retracting the camera, and will react when the deployed camera is broken by aerodynamic forces.

It *might* be possible to use MASDeployableCamera to automatically track a target.  I know it can track the sun, since it uses a KSP module that is also used for solar panels.  If this feature could be interesting, I will do some extra research.

**Comment by Alexustas** [comment]
I have a very strange glitch with sky rendering

video: https://youtu.be/Atetl3ZxIAc

no mods, only MM, MAS and RPM
Tell me what other information you need from me, I will provide everything you need

**Comment by Alexustas** [comment]
FoV marker

video: https://youtu.be/uO9Mxo9E9CM

the marker is updated only when the part is placed

**Comment by Alexustas** [comment]
**Access to camera limits**

I could not find the function to get the data about the active camera limits

**Comment by MOARdV** [comment]
I will put these issues in Issue #133
