### ISSUE TITLE
Feature: bridge Kerbalscript to MAS

### ISSUE THREAD

**Issue by sebseb7** [MOARdV/AvionicsSystems#83]
I would like to display values from kebalscript on instruments and would like to get MAS button events in kerbalscript.

**Comment by MOARdV** [comment]
I'm not familiar with the Kerbalscript mod and I haven't seen it on the forum, so I am probably not going to be the right person to make a bridge for it.  Do you have a link to it?

**Comment by MOARdV** [comment]
I should also note - MAS functionality is limited when the player is not in IVA, and it is also unavailable if the craft is uncrewed, so it will not work on probes, for instance.

**Comment by sebseb7** [comment]
I do all my mission-scripting in kOS. 

https://ksp-kos.github.io/KOS/index.html

**Comment by MOARdV** [comment]
Ah, okay.  This is kOS.

Short answer remains, I won't be making a bridge.

I don't use the mod, and I don't have the spare time to learn how to use it in order to integrate it with MAS.  If someone else wants to tackle building an interface, they're welcome to do so.  All of the key functionality in MAS is accessible through a public API, and I'm willing to provide pointers as needed, But it's not something I'm willing to work on and support, since it's not a mod I use.
